default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # could9
  # username: 'username'
  # password: 'password'
  # host: <%= ENV['IP'] %>

development:
  <<: *default
  database: top_eleven_manager_development

test:
  <<: *default
  database: top_eleven_manager_test
